name: Build & Test using Conda (Meson)

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:
    # Allow to run manually

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Meson
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: ${{ github.event_name == 'pull_request' }}
      max-parallel: ${{ github.event_name == 'pull_request' && 2 || 6 }}
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.9', '3.10', '3.11']
        # Optional environment is disabled for now as its not yet working
        # environment: [environment, environment-optional]
        conda-env: [environment]

    steps:
      - uses: actions/checkout@v4

      - name: Create conda environment files
        run: ./bootstrap-conda

      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ hashFiles('src/environment-3.11.yml') }}

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge
          channel-priority: true
          activate-environment: sage
          environment-file: src/${{ matrix.conda-env }}-${{ matrix.python }}.yml

      - name: Print Conda environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Bootstrap
        shell: bash -l {0}
        run: ./bootstrap

      - name: Build
        shell: bash -l {0}
        run: |
          pip install --no-build-isolation --config-settings=builddir=builddir --editable .

      - name: Test
        if: success() || failure()
        shell: bash -l {0}
        run: ./sage -python -m pytest -c src/tox.ini --doctest-modules src
